name: ml4t
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.6.1
  - arrow-cpp=0.11.1
  - asn1crypto=0.24.0
  - astor=0.7.1
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - autopep8=1.4.3
  - backcall=0.1.0
  - beautifulsoup4=4.6.3
  - binutils_impl_linux-64=2.28.1
  - binutils_linux-64=7.2.0
  - blas=1.0
  - blosc=1.14.4
  - bokeh=1.0.2
  - boost-cpp=1.68.0
  - boto=2.49.0
  - boto3=1.9.66
  - botocore=1.12.67
  - bottleneck=1.2.1
  - bz2file=0.98
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2018.11.29
  - cairo=1.14.12
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cloudpickle=0.6.1
  - colorlover=0.2.1
  - cryptography=2.4.2
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask-core=1.0.0
  - dbus=1.13.2
  - decorator=4.3.0
  - docutils=0.14
  - empyrical=0.3.4
  - entrypoints=0.2.3
  - expat=2.2.6
  - fastparquet=0.2.1
  - ffmpeg=4.0.2
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gast=0.2.1.post0
  - gcc_impl_linux-64=7.2.0
  - gcc_linux-64=7.2.0
  - gettext=0.19.8.1
  - gflags=2.2.2
  - glib=2.56.2
  - glog=0.3.5
  - gmp=6.1.2
  - gnutls=3.5.19
  - graphite2=1.3.13
  - graphviz=2.40.1
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.2.0
  - gxx_linux-64=7.2.0
  - h5py=2.8.0
  - harfbuzz=1.9.0
  - hdf5=1.10.2
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.8
  - imageio=2.4.1
  - inflection=0.3.1
  - intel-openmp=2019.1
  - ipydatawidgets=4.0.0
  - ipykernel=5.1.0
  - ipyscales=0.3.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - ipyvolume=0.5.1
  - ipywebrtc=0.4.3
  - ipywidgets=7.4.2
  - jasper=2.0.14
  - jedi=0.13.2
  - jinja2=2.10
  - jmespath=0.9.3
  - joblib=0.13.0
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.4
  - jupyter_console=6.0.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.0
  - jupyter_core=4.4.0
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.4
  - jupyter_nbextensions_configurator=0.4.0
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - kiwisolver=1.0.1
  - libboost=1.67.0
  - libedit=3.1.20170329
  - libevent=2.1.8
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libgpuarray=0.7.6
  - libiconv=1.15
  - libopencv=3.4.2
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lightgbm=2.2.1
  - llvmlite=0.26.0
  - lxml=4.2.5
  - lz4-c=1.8.1.2
  - lzo=2.10
  - mako=1.0.7
  - markdown=2.6.11
  - markupsafe=1.1.0
  - mistune=0.8.4
  - mkl=2019.1
  - mkl-service=1.1.2
  - mkl_fft=1.0.6
  - mkl_random=1.0.2
  - more-itertools=4.3.0
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=6.1
  - nettle=3.3
  - networkx=2.2
  - ninja=1.8.2
  - nltk=3.4
  - notebook=5.7.4
  - numba=0.41.0
  - numexpr=2.6.8
  - olefile=0.46
  - opencv=3.4.2
  - openh264=1.8.0
  - openssl=1.1.1b
  - packaging=18.0
  - pandas=0.23.4
  - pandas-datareader=0.7.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parquet-cpp=1.5.1
  - parso=0.3.1
  - patsy=0.5.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pillow=5.3.0
  - pip=18.1
  - pixman=0.34.0
  - plotly=3.4.2
  - pluggy=0.8.0
  - prometheus_client=0.5.0
  - prompt_toolkit=2.0.7
  - protobuf=3.6.1
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.7.0
  - py-opencv=3.4.2
  - pycodestyle=2.4.0
  - pycparser=2.19
  - pygments=2.3.1
  - pygpu=0.7.6
  - pymc3=3.5
  - pyopenssl=18.0.0
  - pyparsing=2.3.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pytables=3.4.4
  - pytest=4.0.2
  - python=3.6.8
  - python-dateutil=2.7.5
  - python-graphviz=0.8.4
  - python-snappy=0.5.3
  - pythreejs=2.0.2
  - pytorch=1.0.0
  - pytz=2018.7
  - pywavelets=1.0.1
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.7
  - qtconsole=4.4.3
  - quandl=3.4.5
  - readline=7.0
  - requests=2.21.0
  - retrying=1.3.3
  - s3transfer=0.1.13
  - scikit-image=0.14.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=40.6.3
  - sip=4.19.8
  - six=1.12.0
  - smart_open=1.7.1
  - snappy=1.1.7
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tensorboard=1.12.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - terminado=0.8.1
  - testpath=0.4.2
  - theano=1.0.2
  - thrift=0.11.0
  - thrift-cpp=0.11.0
  - tk=8.6.8
  - toolz=0.9.0
  - torchvision=0.2.1
  - tornado=5.1.1
  - tqdm=4.28.1
  - traitlets=4.3.2
  - traittypes=0.2.1
  - umap-learn=0.3.7
  - urllib3=1.24.1
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.32.3
  - widgetsnbextension=3.4.2
  - wrapt=1.10.11
  - x264=1!152.20180717
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.6
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-libxext=1.3.3
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.9
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zstd=1.3.3
  - pip:
    - bleach==3.0.2
    - cython==0.29.2
    - gensim==3.6.0
    - google-pasta==0.1
    - hdbscan==0.8.18
    - kneed==0.1.0
    - livelossplot==0.3.0
    - matplotlib==2.2.3
    - mock==2.0.0
    - numpy==1.15.1
    - pbr==5.1.1
    - pyfinance==1.1.1
    - scikit-learn==0.20.0
    - scikit-optimize==0.5.2
    - tb-nightly==1.13.0a20190107
    - xlrd==0.9.0
    - xmltodict==0.11.0

